version: "3.8"

services:
  create_service:
    build: ./services/create_service/app
    container_name: create_service
    ports:
      - "${PORT_CREATE:-3020}:${PORT_CREATE:-3020}"
    env_file:
      - services/create_service/app/.env
    networks:
      - planner_network

  delete_service:
    build: services/delete_services/app
    container_name: delete_services
    ports:
      - "${PORT_DELETE:-3021}:${PORT_DELETE:-3021}"
    env_file:
      - services/delete_services/app/.env
    networks:
      - planner_network

  read_service:
    build: services/read_services/app
    container_name: read_services
    ports:
      - "${PORT_READ:-3022}:${PORT_READ:-3022}"
    env_file:
      - services/read_services/app/.env
    networks:
      - planner_network

  update_service:
    build: services/update_services/app
    container_name: update_services
    ports:
      - "${PORT_UPDATE:-3024}:${PORT_UPDATE:-3024}"
    env_file:
      - services/update_services/app/.env
    networks:
      - planner_network

  webhook_service:
    build: webhooks
    container_name: webhook_services
    ports:
      - "${PORT_WEBHOOK:-3030}:${PORT_WEBHOOK:-3030}"
    env_file:
      - webhooks/.env
    networks:
      - planner_network
networks:
  planner_network:
    driver: bridge

volumes:
  postgres_data:
