# Usar una imagen base oficial de Node.js
FROM node:16

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app 

# Copiar el package.json y package-lock.json 
COPY package*.json ./
 
# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación escucha
EXPOSE 3010

# Comando para ejecutar la aplicación
CMD ["node", "server.js"]
