# Usar una imagen base oficial de Node.js
FROM node:18-alpine

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app
# Eliminar node_modules si existe
RUN rm -rf node_modules
# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install 

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto en el que escucha la aplicación
EXPOSE 3002


# Comando para ejecutar la aplicación
CMD ["node", "index.js"]
