name: Build, Push, and Deploy Create Availability

on:
  push:
    branches: [ "QA" ]
    paths:
      - "BACKEND/tareas-service/**"

jobs:
  build-and-push-tareas-service:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build Docker image
        run: |
          cd BACKEND/tareas-service/
          docker build \
            --label "commit_sha=${{ github.sha }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/tareas-service-microservices:latest .

      - name: 🚀 Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tareas-service-microservices:latest

  deploy-aws-tareas-service:
    runs-on: ubuntu-latest
    needs: build-and-push-tareas-service
    steps:
      - name: 🔑 Set permissions for private key
        run: |
          echo "${{ secrets.AWS_EC2_KEY2 }}" > key.pem
          chmod 600 key.pem

      - name: 🚀 Deploy Docker Container on AWS Ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.AWS_EC2_HOST_M7 }} << "EOF"

          # Actualizar paquetes en Ubuntu
          sudo apt update -y && sudo apt upgrade -y

          # Verificar si Docker ya está instalado
          if ! command -v docker &> /dev/null; then
            echo "🛠 Instalando Docker..."
            sudo apt install -y ca-certificates curl gnupg
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt update -y
            sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo usermod -aG docker ubuntu
            sudo systemctl start docker
            sudo systemctl enable docker
          else
            echo "✅ Docker ya está instalado."
          fi

          # Eliminar contenedor antiguo si existe
          sudo docker stop tareas-service-microservices || true
          sudo docker rm tareas-service-microservices || true
          
          # Descargar y ejecutar el nuevo contenedor con la imagen correcta
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/tareas-service-microservices:latest
          sudo docker run -d -p 8083:8083 --name tareas-service-microservices \
            ${{ secrets.DOCKER_USERNAME }}/tareas-service-microservices:latest
          
          # Verificar contenedores en ejecución
          sudo docker ps -a
          
          EOF
