name: Build, Push, and Deploy update Availability

on:
  push:
    branches: [ "QA" ]
    paths:
      - "BACKEND/academic-events/update-event-service/**"  # Cambios en esta carpeta activan el pipeline

jobs:
  build-and-push-ae-update:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          cd BACKEND/academic-events/update-event-service/
          docker build \
            --label "commit_sha=${{ github.sha }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/ae-update-microservices:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ae-update-microservices:latest

  deploy-ae-update:
    needs: build-and-push-ae-update
    runs-on: ubuntu-latest
    steps:
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.AWS_EC2_KEY2 }}" > key.pem
          chmod 600 key.pem

      - name: Deploy Docker Container on AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_M6 }} << "EOF"
          sudo yum update -y
          if ! command -v docker &> /dev/null; then
            sudo yum install -y docker
          fi
          sudo systemctl start docker
          sudo systemctl enable docker

          sudo docker stop ae-update-microservices || true
          sudo docker rm ae-update-microservices || true
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ae-update-microservices:latest
          sudo docker run -d -p 8094:8094 --name ae-update-microservices ${{ secrets.DOCKER_USERNAME }}/ae-update-microservices:latest

          sudo docker ps -a
          EOF